import type { Metadata } from "next";
import '@/styles/globals.css'
import { Toaster } from "sonner";
import { ThemeProvider } from "./theme-provider";
import inter from "@/site/font";

export const metadata: Metadata = {
  title: "PrismaFlow",
  description: "Generated by Zukes",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
